import streamlit as st
import sqlite3
import os
import textwrap
from io import BytesIO
from datetime import datetime, timedelta
from langchain_community.vectorstores import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings, 
ChatGoogleGenerativeAI
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

# --- 1. CONFIG & SECURITY ---
st.set_page_config(page_title="Fiscal Navigator", page_icon="🏛️")

# CLOUD SECURITY
if "GOOGLE_API_KEY" in st.secrets:
    os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
else:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv())

if not os.getenv("GOOGLE_API_KEY"):
    st.error("🚨 CRITICAL: API Key not found. Please configure secrets.")
    st.stop()

# --- 2. DATABASE ENGINE (Safe Mode) ---
DB_NAME = "fiscal_users.db"
def init_db():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    # SPLIT COMMANDS
    p1 = "CREATE TABLE IF NOT EXISTS logs "
    p2 = "(email TEXT, timestamp DATETIME)"
    c.execute(p1 + p2)
    conn.commit()
    conn.close()

def check_limit(email):
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    one_day_ago = datetime.now() - timedelta(days=1)
    # SPLIT QUERY
    q1 = "SELECT count(*) FROM logs "
    q2 = "WHERE email=? AND timestamp > ?"
    c.execute(q1 + q2, (email, one_day_ago))
    count = c.fetchone()[0]
    conn.close()
    return count < 3

def log_usage(email):
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    # SPLIT INSERT
    i1 = "INSERT INTO logs "
    i2 = "VALUES (?, ?)"
    c.execute(i1 + i2, (email, datetime.now()))
    conn.commit()
    conn.close()

init_db()

# --- 3. THE BRAIN (LangChain + Gemini) ---
@st.cache_resource
def load_brain():
    embeddings = 
GoogleGenerativeAIEmbeddings(model="models/embedding-001")
    vector_db = Chroma(persist_directory="chroma_db", 
embedding_function=embeddings)
    
    # SHORT PROMPT LINES
    l1 = 'You are the "Fiscal Navigator," an elite financial 
strategist.\n'
    l2 = 'MISSION: Analyze user situation against CRA/IRS/HUD context.\n'
    l3 = 'Find the "Yes." Provide Strategy, Verdict, and Evidence.\n'
    l4 = 'CONTEXT: {context}\nQUESTION: {question}'
    sys_prompt = l1 + l2 + l3 + l4
    
    PROMPT = PromptTemplate(template=sys_prompt, 
input_variables=["context", "question"])
    
    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", 
temperature=0.1)
    
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=vector_db.as_retriever(search_kwargs={"k": 4}),
        return_source_documents=True,
        chain_type_kwargs={"prompt": PROMPT}
    )
    return qa_chain

# --- 4. PDF ENGINE ---
def create_pdf(text, sources):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "CONFIDENTIAL: STRATEGY ADDENDUM")
    p.setFont("Helvetica", 10)
    # SAFE FOOTER
    footer = "Generated by Fiscal Navigator | VibeCodeX Architecture"
    p.drawString(50, height - 70, footer)
    p.line(50, height - 80, width - 50, height - 80)
    
    text_obj = p.beginText(50, height - 120)
    text_obj.setFont("Helvetica", 11)
    for line in text.split('\n'):
        for wrap in textwrap.wrap(line, 90):
            text_obj.textLine(wrap)
        text_obj.textLine(" ")
    p.drawText(text_obj)
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

# --- 5. THE INTERFACE ---
st.title("🇺🇸 The Fiscal Navigator")
st.caption("Cloud Edition | Powered by Gemini 2.0")

col1, col2 = st.columns(2)
with col1:
    email = st.text_input("Enter Email to Unlock:")
with col2:
    st.info("🔒 Secure Session Active")

query = st.text_area("Describe your objective:", height=100)

# SAFE DISCLAIMER TEXT
disc_text = "I acknowledge this is AI guidance, not legal advice."
agree = st.checkbox(disc_text)

if st.button("Generate Strategy", type="primary"):
    if not email or "@" not in email:
        st.warning("⚠️ Valid email required.")
    elif not agree:
        st.warning("⚠️ Please accept the disclaimer.")
    elif not check_limit(email):
        st.error("🚫 DAILY LIMIT REACHED. Upgrade to Pro.")
    else:
        with st.spinner("🔍 Consulting Federal Database..."):
            try:
                brain = load_brain()
                result = brain.invoke({"query": query})
                
                log_usage(email)
                
                answer = result['result']
                sources = [doc.metadata.get('source', 'Unknown') for doc 
in result['source_documents']]
                
                st.success("Analysis Complete")
                st.write(answer)
                
                pdf = create_pdf(answer, list(set(sources)))
                st.download_button("📄 Download Official PDF", pdf, 
"Strategy.pdf", "application/pdf")
                
            except Exception as e:
                st.error(f"System Error: {e}")
