import streamlit as st
import requests
import db  # Import our new database manager
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from io import BytesIO
import textwrap
import re

# --- HELPER: VALIDATE EMAIL ---
def is_valid_email(email):
    return re.match(r"[^@]+@[^@]+\.[^@]+", email)

# --- PDF GENERATION ENGINE ---
def create_pdf(strategy_text, sources):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "CONFIDENTIAL: STRATEGY ADDENDUM")
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 70, "Generated by Fiscal Navigator | VibeCodeX Architecture")
    p.line(50, height - 80, width - 50, height - 80)
    text_object = p.beginText(50, height - 120)
    text_object.setFont("Helvetica", 11)
    lines = strategy_text.split('\n')
    for line in lines:
        wrapped_lines = textwrap.wrap(line, width=90) 
        for w_line in wrapped_lines:
            text_object.textLine(w_line)
        text_object.textLine(" ") 
    p.drawText(text_object)
    p.setFont("Helvetica-Oblique", 9)
    p.setFillColor(colors.darkblue)
    p.drawString(50, 100, "VERIFIED LEGAL SOURCES:")
    y_pos = 85
    for source in sources:
        clean_source = source.replace("policy_data/", "").replace(".pdf", "")
        p.drawString(50, y_pos, f"• {clean_source}")
        y_pos -= 15
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

# --- MAIN APP INTERFACE ---
st.set_page_config(page_title="Fiscal Navigator", page_icon="🏛️")

st.title("🇺🇸 The Fiscal Navigator")
st.caption("AI-Powered Corporate Strategist")
st.markdown("---")

# --- LEAD GENERATION GATE ---
col1, col2 = st.columns(2)
with col1:
    email = st.text_input("Enter your work email to unlock analysis:")
with col2:
    st.info("🔒 Your email is used to save your session.")

legal_check = st.checkbox("I understand this is AI-generated guidance, not legal advice.")

lbl = "Describe your objective (e.g., CRA Funding, Tax Strategy):"
placeholder = "Example: Draft a Purpose Clause for my LLC to qualify for CRA credits."
query = st.text_area(lbl, height=100, placeholder=placeholder)

if st.button("Analyze & Draft Document", type="primary"):
    if not email or not is_valid_email(email):
        st.warning("⚠️ Please enter a valid email address to proceed.")
    elif not legal_check:
        st.warning("⚠️ You must acknowledge the legal disclaimer.")
    elif not query:
        st.warning("Please enter a command first.")
    else:
        # CHECK THE DATABASE LIMIT
        if db.check_limit(email):
            with st.spinner("🔍 Analyzing Law & Drafting Strategy..."):
                try:
                    response = requests.post(
                        "http://127.0.0.1:8000/analyze", 
                        json={"question": query}
                    )
                    
                    if response.status_code == 200:
                        data = response.json()
                        if "error" in data:
                            st.error(f"🚨 Error: {data['error']}")
                        else:
                            # LOG THE USAGE
                            db.log_usage(email)
                            
                            st.success("Strategy Generated")
                            st.markdown("### 📝 Strategic Output")
                            st.write(data.get("answer", "No answer."))
                            
                            pdf_file = create_pdf(data.get("answer", ""), data.get("verified_sources", []))
                            
                            st.download_button(
                                label="📄 DOWNLOAD LEGAL ADDENDUM (PDF)",
                                data=pdf_file,
                                file_name="Fiscal_Navigator_Strategy.pdf",
                                mime="application/pdf"
                            )
                            
                            st.markdown("---")
                            st.caption("📚 Cited Regulations:")
                            for source in data.get("verified_sources", []):
                                st.code(source)
                    else:
                        st.error(f"Server Error: {response.status_code}")
                except Exception as e:
                    st.error(f"Connection Error: {e}")
        else:
            # LIMIT REACHED
            st.error("🚫 DAILY LIMIT REACHED")
            st.markdown("""
            **You have used your 3 free Strategy Drafts for today.**
            
            To generate more documents immediately:
            - Wait 24 hours for reset.
            - **[Upgrade to Pro ($29/mo)]** for unlimited legal drafting.
            """)

st.markdown("---")
st.markdown("[📍 Check your Census Tract here](https://geomap.ffiec.gov/FFIECGeocMap/GeocodeMap1.aspx) | *System Architecture by VibeCodeX*")
